### ISSUE TITLE
error after Provider start

### ISSUE THREAD

**Issue by Elufimov** [timkoopmans/watirgrid#5]
RubyGems Environment:
RUBYGEMS VERSION: 1.8.11
RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [i386-mingw32]
INSTALLATION DIRECTORY: C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1
RUBY EXECUTABLE: C:/RailsInstaller/Ruby1.9.2/bin/ruby.exe
EXECUTABLE DIRECTORY: C:/RailsInstaller/Ruby1.9.2/bin
RUBYGEMS PLATFORMS:
  ruby
  x86-mingw32
GEM PATHS:
   C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1
   C:/Users/Hulit Packard/.gem/ruby/1.9.1
GEM CONFIGURATION:
   :update_sources => true
   :verbose => true
   :benchmark => false
   :backtrace => false
   :bulk_threshold => 1000
REMOTE SOURCES:
   http://rubygems.org/

require 'watirgrid'
=> true

> > controller = Controller.new
> > controller.start
> > controller = Controller.new
> > => #<Controller:0x2b17a20 @drb_server_host="192.168.0.134", @drb_server_port=0, @ring_server_host="192.168.0.134", @ring_server_port=7647, @acls=nil, @log=#<Logger:0x2b13658 @progname=nil, @level=1, @default_formatter=#<Logger::Formatter:0x2b13640 @datetime_format="%Y-%m-%d %H:%M:%S ">, @formatter=nil, @logdev=#<Logger::LogDevice:0x2b135b0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x2b13598 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x2b13568>>>>>
> > controller.start
> > I, [2011-10-11 14:06:18 #6184]  INFO -- : Controller started on : druby://192.168.0.134:52568
> > => nil
> > 1.upto(2) do
> >   provider = Provider.new(:driver => 'webdriver')
> >   provider.start
> > end
> > 1.upto(2) do
> >   provider = Provider.new(:driver => 'webdriver')
> >   provider.start
> > end
> > I, [2011-10-11 14:06:29 #6184]  INFO -- : Provider started on   : druby://192.168.0.134:52570
> > NoMethodError: undefined method `each' for "192.168.0.134":String
> >     from C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/rinda/ring.rb:180:in`lookup_ring'
> >     from C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/rinda/ring.rb:202:in `block in lookup_ring_any'

**Comment by Elufimov** [comment]
but under 1.8.7 it works
RubyGems Environment:
RUBYGEMS VERSION: 1.8.11
RUBY VERSION: 1.8.7 (2011-06-30 patchlevel 352) [i386-mingw32]
INSTALLATION DIRECTORY: C:/RailsInstaller/Ruby187/lib/ruby/gems/1.8
RUBY EXECUTABLE: C:/RailsInstaller/Ruby187/bin/ruby.exe
EXECUTABLE DIRECTORY: C:/RailsInstaller/Ruby187/bin
RUBYGEMS PLATFORMS:
  ruby
  x86-mingw32
GEM PATHS:
   C:/RailsInstaller/Ruby187/lib/ruby/gems/1.8
   C:/Users/Hulit Packard/.gem/ruby/1.8
GEM CONFIGURATION:
   :update_sources => true
   :verbose => true
   :benchmark => false
   :backtrace => false
   :bulk_threshold => 1000
REMOTE SOURCES:
   http://rubygems.org/

**Comment by timkoopmans** [comment]
The problem is that in Ruby 1.9.2 each() has been removed from String and it is no longer Enumerable. I'm not sure yet on the best way to (monkey?) patch this ... Technically this is a bug in the core library for Rinda.

**Comment by Elufimov** [comment]
In Ruby 1.9.3, nothing has changed. = (No planned a translation grid for the latest version of Ruby? Grid is the only thing that keeps me on 1.8.7

**Comment by timkoopmans** [comment]
You can still use watirgrid in 1.9.2, you just can't broadcast for a controller (from the provider).

So if you start a controller

```
» controller
I, [2011-11-01 20:23:39 #49171]  INFO -- : Controller started on : druby://203.51.48.187:11235
```

Then start a provider with no -c parameter, you'll get the error described in this issue. But if you provide the controller URI it will work, as it avoids the broadcast using core Ruby libraries (which need to be fixed)

```
» provider -c druby://203.51.48.187:11235 -d webdriver -b chrome
I, [2011-11-01 20:25:25 #49264]  INFO -- : Provider started on   : druby://203.51.48.187:54289
I, [2011-11-01 20:25:25 #49264]  INFO -- : Controller found on   : druby://203.51.48.187:11235
I, [2011-11-01 20:25:25 #49264]  INFO -- : Provider registered   : druby://203.51.48.187:11235
```

Similar thing if you're doing it in code

```
provider = Provider.new(:driver => 'webdriver', :controller_uri => 'druby://203.51.48.187:11235' )
```

**Comment by Elufimov** [comment]
1.9.2

```
controller = Controller.new(:drb_server_host => "127.0.0.1", :drb_server_port => "1234")
controller.start

provider = Provider.new(:browser_type => 'firefox', :controller_uri => "druby://127.0.0.1:1234")
provider.start
```

I, [2011-11-01 14:19:48 #6532]  INFO -- : Controller started on : druby://127.0.0.1:1234
I, [2011-11-01 14:19:48 #6532]  INFO -- : Provider started on   : druby://192.168.0.134:57826
I, [2011-11-01 14:19:48 #6532]  INFO -- : Controller found on   : druby://127.0.0.1:1234
I, [2011-11-01 14:19:48 #6532]  INFO -- : Provider registered   : druby://127.0.0.1:1234
C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/rinda/ring.rb:180:in `lookup_ring': undefined method`each' for "192.168.0.134":String (NoMethodError)
    from C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/rinda/ring.rb:202:in `block in lookup_ring_any'

**Comment by timkoopmans** [comment]
Can you please show me the rest of your code... It looks like the controller and provider are starting OK.

I think it might be your watirgrid init ... You'll need to specify the controller_uri there as well e.g.

```
Watir::Grid.control(:browser_type => 'firefox', :controller_uri => 'druby://127.0.0.1:1234') do |browser, index|
  p "I am browser index #{index}"
  browser.goto "http://google.com"
  p browser.title
  browser.text_field(:name, 'q').set("watirgrid")
  browser.button(:name, "btnI").click
  browser.close
end
```

**Comment by Elufimov** [comment]
Сode lives here https://github.com/Elufimov/AC-76

**Comment by timkoopmans** [comment]
Yeah this is the problem in ur code

```
Watir::Grid.control({})
```

Need to specify the :controller_uri in that hash aswell, otherwise it tries to do the broadcast on UDP thing ... (which for Rinda is broken in 1.9.x)

**Comment by Elufimov** [comment]
Thank you very much for your help! Maybe we should bring these details to work with newer versions of ruby in readme?

**Comment by timkoopmans** [comment]
Good idea. Done
https://github.com/90kts/watirgrid/blob/master/README.rdoc
